pipeline:
  docker:
    image: plugins/docker
    repo: stefandorresteijn/graphqlexample
    tags: latest
    username: stefandorresteijntest
    password: testaccount123

  ecs:
    image: peloton/drone-ecs
    service: staging-cluster
    region: eu-central-1
    family: ecs-test-deploy
    image_name: stefandorresteijn/graphqlexample
    image_tag: latest
    port_mappings:
      - 80 8080
    memory: 128
    secrets: [ ecs_access_key, ecs_secret_key ]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: esports-core-dev
    username: drone
    template: >
      {{#success build.status}}
        Build #{{build.number}} succeeded. Good job.
      {{else}}
        Build #{{build.number}} failed. Fix me please.
      {{/success}}